### ISSUE TITLE
Problem accessing running container on ACI

### ISSUE THREAD

**Issue by jpcrs** [joeduffy/infrastructure-as-code-workshop#17]
There are some inconsistencies in the `Workshop 03 - Deploying Containers to Azure Container Instances`

At first the `Endpoint` property is set using `$"https://{group.Fqdn}"`, but after you deploy the Nginx with a simple HTML, it doesn't say to update to `http://`, so you can't access the deployed container with the exported URL.

Also in the guide uses `curl $(pulumi stack output url)`, but it should be  `curl $(pulumi stack output Endpoint)`.

https://github.com/pulumi/infrastructure-as-code-workshop/blame/master/labs/azure/csharp/03-aci/README.md#L245

**Comment by mikhailshilkov** [comment]
Thank you, changed to `http` everywhere
