### ISSUE TITLE
[nitpick] New C# Project does not contain the `Pulumi.dev.yaml` file

### ISSUE THREAD

**Issue by moinoviimir** [joeduffy/infrastructure-as-code-workshop#22]
Repro:
- go through Preparation;
- run the [first step](https://github.com/pulumi/infrastructure-as-code-workshop/blob/master/labs/azure/csharp/01-iac/01-creating-a-new-project.md) to the end.

Expected:
- `Pulumi.dev.yaml` file in the folder

Observed:
- no such file in the folder
- the file only appears upon running `pulumi config set azure:location westus2`.

Suggestion: remove the file from the end list.

**Comment by mikhailshilkov** [comment]
You are right! Removed!
