### ISSUE TITLE
Azure Lab 02-serverless - Azure.Storage.SharedAccessSignature.SignedBlobReadUrl no longer accepts Azure.Storage.ZipBlobArgs 

### ISSUE THREAD

**Issue by Sealjay** [joeduffy/infrastructure-as-code-workshop#38]
Cannot convert from 'Pulumi.Azure.Storage.ZipBlob' to 'Pulumi.Azure.Storage.Blob' when passing a blob to Azure.Storage.SharedAccessSignature.SignedBlobReadUrl.

**Comment by mikhailshilkov** [comment]
Gonna fix this in #37. PRs are welcome too ;)

**Comment by Sealjay** [comment]
There we go, some tweaks @mikhailshilkov  :)
