### ISSUE TITLE
Python - Split up lab04

### ISSUE THREAD

**Issue by metral** [joeduffy/infrastructure-as-code-workshop#45]
Split up https://github.com/pulumi/infrastructure-as-code-workshop/tree/master/labs/aws/python/lab-04

into separate labs for a) creating the cluster, and b) using the cluster

**Comment by stack72** [comment]
@metral we need to do this for all 4 labs right?

**Comment by metral** [comment]
@stack72 Yup, here are the rest of the issues:

- #46 
- #47 
- #48
