### ISSUE TITLE
GCP labs

### ISSUE THREAD

**Issue by confiq** [joeduffy/infrastructure-as-code-workshop#56]
Can we get a notification when GCP labs are done? 
Good example would be to close this issue for example. 

The thing is, I would love to look at this labs but I don't have a way to get a notification when they are done.

**Comment by stack72** [comment]
Hi @confiq 

Not sure what you mean by "videos" - can you elaborate more?

Paul

**Comment by confiq** [comment]
Hi Paul, 
I should be more clear, I've edited my original question and the title. 

The idea is that I would like to be notified when these labs are done so I would share it with my coworkers. 
I could check once a month/week this repo but we might use also an issue/task so people will be notified. 
If you think this is redundant feel free to close the issue. 

Cheers

**Comment by stack72** [comment]
Oh I see - my apologies here - yes, I plan to add these starting next week!

I will leave this open and can close it out when it's done :)
