### ISSUE TITLE
no python labs

### ISSUE THREAD

**Issue by amichib** [joeduffy/infrastructure-as-code-workshop#9]
there is only labs in ts.
please add examples for python as well.
thanks!

**Comment by stack72** [comment]
Thanks @amichib 

You are indeed correct and this is something that I shall be adding asap! The structure of this repo will also change accordingly :) Thanks for coming along today!!

Paul

**Comment by stack72** [comment]
@amichib hey - just a heads up that Python labs have started being added in #11
